# Generated by Django 5.2.6 on 2025-09-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('available_quantity', models.IntegerField(help_text='Current available quantity')),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Bought price per unit', max_digits=10)),
                ('bought_quantity', models.IntegerField(help_text='Quantity bought in this purchase')),
                ('morning_dose', models.IntegerField(default=0, help_text='Dose for morning (e.g., number of pills)')),
                ('lunch_dose', models.IntegerField(default=0, help_text='Dose for lunch (e.g., number of pills)')),
                ('dinner_dose', models.IntegerField(default=0, help_text='Dose for dinner (e.g., number of pills)')),
                ('timing', models.CharField(choices=[('before', 'Before Meal'), ('after', 'After Meal')], default='after', help_text='Take before or after meals', max_length=10)),
                ('purchase_date', models.DateField(auto_now_add=True, help_text='Date of purchase/log entry')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes')),
            ],
        ),
    ]
