# Generated by Django 5.2.6 on 2025-09-05 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Default price per unit', max_digits=10)),
                ('morning_dose', models.IntegerField(default=0, help_text='Dose for morning (e.g., number of pills)')),
                ('lunch_dose', models.IntegerField(default=0, help_text='Dose for lunch (e.g., number of pills)')),
                ('dinner_dose', models.IntegerField(default=0, help_text='Dose for dinner (e.g., number of pills)')),
                ('morning_timing', models.CharField(choices=[('before', 'Before Meal'), ('after', 'After Meal')], default='after', help_text='Timing for morning dose', max_length=10)),
                ('lunch_timing', models.CharField(choices=[('before', 'Before Meal'), ('after', 'After Meal')], default='after', help_text='Timing for lunch dose', max_length=10)),
                ('dinner_timing', models.CharField(choices=[('before', 'Before Meal'), ('after', 'After Meal')], default='after', help_text='Timing for dinner dose', max_length=10)),
                ('available_quantity', models.IntegerField(default=0, help_text='Current available quantity (auto-updated)')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought_quantity', models.IntegerField(help_text='Quantity bought in this purchase')),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Price per unit for this purchase', max_digits=10)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='Logs.medicine')),
            ],
        ),
    ]
